name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build . -t uqma
      - name: Run image
        run: docker run uqma --help
