name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build image
        run: docker build . -t uqma
      - name: Test train
        run: |
          docker run -tv $(pwd):/mnt ubuntu ls -R /mnt
          docker run -tv $(pwd):/mnt \
            uqma \
            --config=/mnt/configs/config.py \
            --infile=/mnt/data/x_text.csv \
            --outfile=/mnt/params.pkl \
            --config.training.n_iter=1

